global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - localhost:9090
  - job_name: "fastapi-app"
    static_configs:
      - targets: ["fastui_startrek.local:8000"]
