version: "3.7"

services:
  fastui_startrek_svc:
    container_name: fastui_startrek
    hostname: fastui_startrek.local
    build:
      context: .
    working_dir: /src
    volumes:
      - ..:/src:cached
    ports:
      - ${host_http_port}:8000
    command: >
      bash -c "sleep infinity"
    networks:
      fastui_startrek-net:

networks:
  fastui_startrek-net:
