version: "3.7"

services:
  fastui_startrek_svc:
    container_name: fastui_startrek
    hostname: fastui_startrek.local
    build:
      context: .
    working_dir: /src
    volumes:
      - ..:/src:cached
    ports:
      - ${host_http_port}:8000
    command: >
      bash -c "sleep infinity"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - ${host_prometheus_port}:9090
    #volumes:
    #  - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus_config/prometheus.yml:/etc/prometheus/prometheus.yml

networks:
  fastui_startrek-net:
